name: Verification
on:
  pull_request:
  push:
    branches:
      - feat/verification
jobs:
  verify-wire:
    runs-on: [ubuntu-22.04]
    steps:
      - name: 'Checkout your code.'
        uses: actions/checkout@v3

      - name: 'Run Kani on TCP wire.'
        uses: model-checking/kani-github-action@v0.34
        with:
          args: '--solver kissat --output-format=terse --verbose --harness wire::tcp::verification'
  verify-socket:
    runs-on: [ubuntu-22.04]
    steps:
      - name: 'Checkout your code.'
        uses: actions/checkout@v3

      - name: 'Run Kani on TCP socket.'
        uses: model-checking/kani-github-action@v0.34
        with:
          args: '--solver kissat --output-format=terse --verbose --harness socket::tcp::verification'
