name: Verification
on:
  pull_request:
  push:
    branches:
      - feat/verification
jobs:
  run-kani:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout your code.'
        uses: actions/checkout@v3

      - name: 'Run Kani on your code.'
        uses: model-checking/kani-github-action@v0.33
        args: '--enable-unstable --jobs 4 --output-format=terse'
